import React from "react";

const Category = () => {
	const type = [
		"market",
		"establishment",
		"art_gallery",
		"tourist_attraction",
		"shopping_mall",
		"point_of_interest",
		"library",
		"palace",
		"local_government_office",
		"health",
		"park",
		"zoo",
		"aquarium",
		"playground",
		"children",
		"amusement_park",
		"museum",
		"monument",
		"royal",
		"store",
		"religious structure",
		"surfing",
		"hall",
		"premise",
		"bridge",
		"residence",
		"place_of_worship",
		"fort",
		"memorial",
		"culture",
		"theater",
		"buddhist temple",
		"motorsports",
		"movie_theater",
		"finance",
		"church",
		"hindu_temple",
		"food",
		"cafe",
		"restaurant",
		"book_store",
		"place of worship",
		"meditation",
		"transit_station",
		"veterinary_care",
		"stadium",
		"show",
		"grocery_or_supermarket",
		"historic building",
		"mosque",
		"department_store",
		"beauty_salon"
	];
	return <div>d</div>;
};

export default Category;
